### ISSUE TITLE
clobbering files which contain the same name after renaminf

### ISSUE THREAD

**Issue by brotich** [danboid/songrec-rename#1]
- if the folder contains file with the same song, but different filenames, The rename logic will overwrite the renamed song with the last file recognized. 

consider appending int after file name on duplicate files i.e song-artist(n) for duplicate files,

**Comment by danboid** [comment]
Hi Brian

Thanks for pointing that out, I didn't consider that. I have changed the move command to use the no clobber option but that means it simply won't rename additional copies of an existing file within the same directory, only the first instance.

Feel free to submit a patch if you want it to work as you described.
