### ISSUE TITLE
Is there a way to write ID3 tags when recognizing music files?

### ISSUE THREAD

**Issue by gabrielmacedoanac** [danboid/songrec-rename#2]
First, thanks a lot!

Could you write a script that also changes the ID3 tag of music files? It would be great.
I was able to use BASH inline to do some iterations, but what you've done in the script is more sophisticated.

**Comment by danboid** [comment]
Yes it will be possible to add id3 tags when renaming mp3 files that get recognised using something like id3tool. I could add an extra option like -id3 to rewrite the id3 tags and the file name for all recognised mp3s.

I'm super busy with work right now, doing lots of overtime so I might not get round to this for a bit but it won't take long to add so I'll hopefully add it soon.

**Comment by danboid** [comment]
I have added support for using id3tool to add id3 tags to mp3 files. Run songrec-rename with the -i option to add id3 tags.

**Comment by gabrielmacedoanac** [comment]
Thankx a lot!
